src/AppBundle/Entity/Movimiento.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Movimiento
 *
 * @ORM\Table(name="movimiento")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\MovimientoRepository")
 */
class Movimiento
{
    const ENERO ='Enero';
    const FEBRERO= 'Febrero';
    const MARZO= 'Marzo';
    const ABRIL= 'Abril';
    const MAYO= 'Mayo';
    const JUNIO= 'Junio';
    const JULIO= 'Julio';
    const AGOSTO= 'Agosto';
    const SEPTIEMBRE= 'Septiembre';
    const OCTUBRE= 'Octubre';
    const NOVIEMBRE= 'Noviembre';
    const DICIEMBRE= 'Diciembre';
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     * @Assert\NotBlank(message="This field cannot be empty.")
     * @ORM\Column(name="nombre", type="string", length=255)
     */
    private $nombre;

    /**
     * @ORM\ManyToOne(targetEntity="TipoMovimiento", inversedBy="movimiento")
     * @ORM\JoinColumn(name="tipo_id", referencedColumnName="id", onDelete="CASCADE", nullable=false)
     */
    private $tipo;

    /**
     * @var string
     *
     * @ORM\Column(name="descripcion", type="string", length=255)
     */
    private $descripcion;

    /**
     * @var float
     * @Assert\Type(type="float", message="Introduce un valor correcto")
     *@Assert\NotBlank(message="This field cannot be empty.")
     * @ORM\Column(name="cantidad", type="float")
     */
    private $cantidad;

    /**
     * @var string
     *
     * @ORM\Column(name="mes", type="string")
     */
    private $mes;

    public function getTypeName() {
        switch($this->getMes()) {
            case self::ENERO: return 'Enero';
            case self::FEBRERO: return 'Febrero';
            case self::MARZO: return 'Marzo';
            case self::ABRIL: return 'Abril';
            case self::MAYO: return 'Mayo';
            case self::JUNIO: return 'Junio';
            case self::JULIO: return 'Julio';
            case self::AGOSTO: return 'Agosto';
            case self::SEPTIEMBRE: return 'Septiembre';
            case self::OCTUBRE: return 'Octubre';
            case self::NOVIEMBRE: return 'Noviembre';
            case self::DICIEMBRE: return 'Diciembre';
        }
        return '';
    }
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set tipo
     *
     * @param string $tipo
     * @return Movimiento
     */
    public function setTipo($tipo)
    {
        $this->tipo = $tipo;

        return $this;
    }

    /**
     * Get tipo
     *
     * @return string 
     */
    public function getTipo()
    {
        return $this->tipo;
    }

    /**
     * Set descripcion
     *
     * @param string $descripcion
     * @return Movimiento
     */
    public function setDescripcion($descripcion)
    {
        $this->descripcion = $descripcion;

        return $this;
    }

    /**
     * Get descripcion
     *
     * @return string 
     */
    public function getDescripcion()
    {
        return $this->descripcion;
    }

    /**
     * Set cantidad
     *
     * @param integer $cantidad
     * @return Movimiento
     */
    public function setCantidad($cantidad)
    {
        $this->cantidad = $cantidad;

        return $this;
    }

    /**
     * Get cantidad
     *
     * @return integer 
     */
    public function getCantidad()
    {
        return $this->cantidad;
    }

    /**
     * Set mes
     *
     * @param string $mes
     * @return Movimiento
     */
    public function setMes($mes)
    {
        $this->mes = $mes;

        return $this;
    }

    /**
     * Get mes
     *
     * @return string 
     */
    public function getMes()
    {
        return $this->mes;
    }

    /**
     * @return string
     */
    public function getNombre()
    {
        return $this->nombre;
    }

    /**
     * @param string $nombre
     */
    public function setNombre($nombre)
    {
        $this->nombre = $nombre;
    }

    public function __toString()
    {
        // TODO: Implement __toString() method.
        return $this->getNombre();
    }
}

src/AppBundle/Form/MovimientoType.php
<?php

namespace AppBundle\Form;

use AppBundle\Entity\Movimiento;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Regex;

class MovimientoType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nombre', TextType::class, [
                    'label'=>"Movimiento",
                    'empty_data'=>null
            ])
            ->add('descripcion', TextType::class)
            ->add('mes', ChoiceType::class, array(
                'choices' => array(
                    Movimiento::ENERO => Movimiento::ENERO,
                    Movimiento::FEBRERO=> Movimiento::FEBRERO,
                    Movimiento::MARZO=> Movimiento::MARZO,
                    Movimiento::ABRIL=> Movimiento::ABRIL,
                    Movimiento::MAYO=> Movimiento::MAYO,
                    Movimiento::JUNIO=> Movimiento::JUNIO,
                    Movimiento::JULIO=> Movimiento::JULIO,
                    Movimiento::AGOSTO=> Movimiento::AGOSTO,
                    Movimiento::SEPTIEMBRE=> Movimiento::SEPTIEMBRE,
                    Movimiento::OCTUBRE=> Movimiento::OCTUBRE,
                    Movimiento::NOVIEMBRE=> Movimiento::NOVIEMBRE,
                    Movimiento::DICIEMBRE=> Movimiento::DICIEMBRE,
                )), true)
            ->add('cantidad', MoneyType::class, [
                'error_bubbling' => true,
                'constraints' => [
                    new Regex(array('pattern'=>'/\d+(\.\d+)?/','message'=>'must be numeric')),
                ]
            ])
            ->add('tipo', EntityType::class, [
                'class'=>'AppBundle\Entity\TipoMovimiento',
                'choice_label'=>'nombre',
                'label'=>'Tipo',
            ])
            ->add('add', SubmitType::class, array('label' => 'Añadir'));
    }
    
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\Movimiento'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'appbundle_movimiento';
    }


}

src/AppBundle/Controller/MovimientoController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Movimiento;
use Doctrine\DBAL\Types\DateType;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Request;

class MovimientoController extends Controller
{
    /**
     * @Route("/", name="homepage")
     */

    public function indexAction(Request $request){
        $movimiento = new Movimiento();
        $repository=$this->getDoctrine()->getRepository('AppBundle:Movimiento');
        $totalGastos=$repository->calcularTotalGastos();
        $totalIngresos=$repository->calcularTotalIngresos();
        $total=$totalIngresos[0][1]-$totalGastos[0][1];

        $searchMovimiento=$this->createForm('AppBundle\Form\MovimientoFilterType', $movimiento);
        $searchMovimiento->handleRequest($request);

        $page = ($searchMovimiento->isSubmitted()) ? 1 : $request->get('page', 1);
        $queryBuilder=$repository->cargarMovimiento($movimiento->getMes(),$movimiento->getTipo());
        $adapter = new DoctrineORMAdapter($queryBuilder);
        $pagerfanta = new Pagerfanta($adapter);
        $pagerfanta->setMaxPerPage(5);
        $pagerfanta->setCurrentPage($page);

        return $this->render('AppBundle:Movimiento:lista.html.twig', array(
            "movimiento"=>$pagerfanta->getCurrentPageResults(),
            "pager" => $pagerfanta,
            "formSearch"=>$searchMovimiento->createView(),
            "total"=>$total
        ));
    }

//    public function indexAction(Request $request)
//    {
//        // replace this example code with whatever you need
//        $repository=$this->getDoctrine()->getRepository('AppBundle:Movimiento');
//        $movimiento=$repository->findAll();
//        $totalGastos=$repository->calcularTotalGastos();
//        $totalIngresos=$repository->calcularTotalIngresos();
//        $total=$totalIngresos[0][1]-$totalGastos[0][1];
//        $filtro=$this->filter();
//        $filtro->handleRequest($request);
//        if ($filtro->isSubmitted()) {
//            $data = $filtro->getData();
//            $movimiento=$repository->findBy([
//                    "mes"=>$data['mes'],
//                    "tipo"=>$data['tipo'],
//                ]
//            );
//        }
//        return $this->render('AppBundle:Movimiento:lista.html.twig', [
//            "movimiento"=>$movimiento,
//            "total"=>$total,
//            "formSearch"=>$filtro->createView(),
//        ]);
//    }
    /**
     * @Route("add")
     */
    public function add(Request $request)
    {
        $movimiento= new Movimiento();
        $form = $this->createForm('AppBundle\Form\MovimientoType', $movimiento);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $movimiento = $form->getData();
             $em = $this->getDoctrine()->getManager();
             $em->persist($movimiento);
             $em->flush();

            return $this->redirectToRoute('homepage');
        }
        return $this->render('AppBundle:Movimiento:add.html.twig', array(
            'form' => $form->createView(),
        ));
    }

    /**
    * @Route("delete/{id}")
    */
    public function delete($id){
        $repository = $this->getDoctrine()->getRepository('AppBundle:Movimiento');
        $movimiento=$repository->find($id);
        $em = $this->getDoctrine()->getEntityManager();
        $em->remove($movimiento);
        $em->flush();
        return $this->redirectToRoute('homepage');
    }

    public function filter(){
        $form = $this->createForm('AppBundle\Form\MovimientoFilterType');
        return $form;
    }
    /**
     * @Route("resumen/{mes}")
     */
    public function resumenAction($mes=null){
        $repo=$this->getDoctrine()->getRepository('AppBundle:Movimiento');
        $movimiento=$repo->findAll();
        $gastosMes=$repo->resumenGastoMes($mes, 0);
        $ingresosMes=$repo->resumenGastoMes($mes, 1);
        $gastoMes=$gastosMes[0][1];
        $ingresoMes=$ingresosMes[0][1];
        $total=$ingresoMes-$gastoMes;
        return $this->render('AppBundle:Movimiento:resumen.html.twig',[
            "resumen"=>$total,
            "entidad"=>$movimiento,
            "movimiento"=>$gastosMes,
            "mes"=>$mes,
        ]);
    }

}

src/AppBundle/Resources/views/Movimiento/add.html.twig
{% extends 'layout.html.twig' %}
{% block contenido %}
    <div class="row">
        <div class="col-sm-4"></div>
        <div class="col-sm-4">
            {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
            <div class="form-group">
                {{ form_label(form.nombre) }}
                {{ form_widget(form.nombre, {'attr': {'class': 'form-control'}}) }}
            </div>
            <div class="form-group">
                {{ form_label(form.descripcion) }}
                {{ form_widget(form.descripcion, {'attr': {'class': 'form-control'}}) }}
            </div>
            <div class="form-group">
                {{ form_label(form.cantidad) }}
                {{ form_widget(form.cantidad, {'attr': {'class': 'form-control'}}) }}
            </div>
            <div class="form-group">
                {{ form_label(form.mes) }}
                {{ form_widget(form.mes, {'attr': {'class': 'form-control'}}) }}
            </div>
            <div class="form-group">
                {{ form_label(form.tipo) }}
                {{ form_widget(form.tipo, {'attr': {'class': 'form-control'}}) }}
            </div>
            <div class="form-group">
                {{ form_label(form.add) }}
                {{ form_widget(form.add, {'attr': {'class': 'form-control'}}) }}
            </div>
            {{ form_end(form) }}
        </div>
        <div class="col-sm-4"></div>
    </div>


{% endblock %}

src/AppBundle/Resources/views/Movimiento/lista.html.twig
{% extends 'layout.html.twig' %}
{% block contenido %}

    <div class="row margin20px text-center">
        <div class="col-md-12">
            {{ form_start(formSearch, {'attr': {'novalidate': 'novalidate', 'class':'form-inline'}}) }}
            <div class="form-group">
                {{ form_label(formSearch.mes) }}
                {{ form_widget(formSearch.mes, {'attr': {'class': 'form-control'}}) }}
            </div>
            <div class="form-group">
                {{ form_label(formSearch.tipo) }}
                {{ form_widget(formSearch.tipo, {'attr': {'class': 'form-control'}}) }}
            </div>
            <div class="form-group">
                {{ form_label(formSearch.search) }}
                {{ form_widget(formSearch.search, {'attr': {'class': 'form-control'}}) }}
            </div>
            {{ form_end(formSearch) }}
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <table class="table">
                <tr class="bg-info">
                    <th>Nombre</th><th>Descripción</th><th>Mes</th><th>Tipo</th><th>Cantidad</th><th>Borrar</th>
                </tr>
            {% for mov in movimiento %}
                <tr>
                   <td>{{ mov.nombre }}</td>
                   <td>{{ mov.descripcion }}</td>
                   <td>{{ mov.typeName }}</td>
                   <td>{{ mov.tipo.nombre }}</td>
                    {% if mov.tipo.nombre=='GASTO' %}
                        <td class="text-center alert-danger">{{ mov.cantidad }} €</td>
                    {% else %}
                        <td class="text-center alert-success">{{ mov.cantidad }} €</td>
                        {% endif %}
                    <td class="text-center"><span><a class="btn btn-danger" href="{{ path('app_movimiento_delete', {id: mov.id}) }}">x</a></span></td>
                {% endfor %}
                </tr>
                <tr class="text-center">
                    <td>---</td><td>---</td><td>---</td><td>---</td><td>---</td><td>---</td>
                </tr>
                <tr class="text-center gris">
                    <td></td><td></td><td></td><td class="text-right">Total:</td>
                    {% if total < 0 %}
                        <td class="alert-warning"><b>{{ total }} €</b></td>
                        {% else %}
                            <td class="alert-success"><b> {{ total }} €</b></td>
                        {% endif %}
                    <td></td>
                </tr>
            </table>
        </div>
        <div>
            {% if pager.haveToPaginate() %}
                {{ pagerfanta(pager, 'twitter_bootstrap3', {
                    prev_message: 'Anterior',
                    next_message: 'Siguiente'
                }) }}
            {% endif %}
        </div>
    </div>



{% endblock %}

src/AppBundle/Resources/views/Movimiento/resumen.html.twig
{% extends 'layout.html.twig' %}
{% block contenido %}
    <div class="row">
        <div class="col-md-6">
            <h1 class="text-center">{{ mes }}</h1>
        </div>
        <div class="col-md-6">
            {% if resumen < 0 %}
                <h2 class="btn-danger text-center padding10px">{{ resumen }} €</h2>
            {% else %}
                <h2 class="btn-success text-center padding10px">{{ resumen }} €</h2>
            {% endif %}
        </div>
    </div>
    <div class="row padding10px text-center">
        <div class="col-md-3">
            <a type="button" class="btn btn-danger" href="{{ path('app_movimiento_resumen', {'mes':'Enero'}) }}">Enero</a>
        </div>
        <div class="col-md-3">
            <a type="button" class="btn btn-danger" href="{{ path('app_movimiento_resumen', {'mes':'Febrero'}) }}">Febrero</a>
        </div>
        <div class="col-md-3">
            <a type="submit" class="btn btn-danger" href="{{ path('app_movimiento_resumen', {'mes':'Marzo'}) }}">Marzo</a>
        </div>
        <div class="col-md-3">
            <a type="submit" class="btn btn-danger" href="{{ path('app_movimiento_resumen', {'mes':'Abril'}) }}">Abril</a>
        </div>

    </div>
    <div class="row padding10px text-center">
        <div class="col-md-3">
            <a type="button" class="btn btn-danger" href="{{ path('app_movimiento_resumen', {'mes':'Mayo'}) }}">Mayo</a>
        </div>
        <div class="col-md-3">
            <a type="button" class="btn btn-danger" href="{{ path('app_movimiento_resumen', {'mes':'Junio'}) }}">Junio</a>
        </div>
        <div class="col-md-3">
            <a type="submit" class="btn btn-danger" href="{{ path('app_movimiento_resumen', {'mes':'Julio'}) }}">Julio</a>
        </div>
        <div class="col-md-3">
            <a type="submit" class="btn btn-danger" href="{{ path('app_movimiento_resumen', {'mes':'Agosto'}) }}">Agosto</a>
        </div>

    </div>
    <div class="row padding10px text-center">
        <div class="col-md-3">
            <a type="button" class="btn btn-danger" href="{{ path('app_movimiento_resumen', {'mes':'Septiembre'}) }}">Septiembre</a>
        </div>
        <div class="col-md-3">
            <a type="button" class="btn btn-danger" href="{{ path('app_movimiento_resumen', {'mes':'Octubre'}) }}">Octubre</a>
        </div>
        <div class="col-md-3">
            <a type="submit" class="btn btn-danger" href="{{ path('app_movimiento_resumen', {'mes':'Noviembre'}) }}">Noviembre</a>
        </div>
        <div class="col-md-3">
            <a type="submit" class="btn btn-danger" href="{{ path('app_movimiento_resumen', {'mes':'Diciembre'}) }}">Diciembre</a>
        </div>

    </div>
{% endblock %}